# Generated by Django 5.0.6 on 2024-07-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
    ]
