# Generated by Django 5.0.6 on 2024-07-04 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20240704_1543'),
    ]

    operations = [
    ]
